#!/usr/bin/expect -f
set timeout -1
set password [lindex $argv 0]
set user [lindex $argv 1]
set host [lindex $argv 2]

spawn ssh -o StrictHostKeyChecking=no $user@$host "cd ~/sigex-gateway && sudo docker compose down sigex-gateway && tar -xzf ~/gateway.tar.gz && sudo docker compose build --no-cache sigex-gateway && sudo docker compose up -d sigex-gateway"
expect {
    "*assword:*" {
        send "$password\r"
        exp_continue
    }
    eof
}
